The issue with the script is that it only works with factors of 2.
 Any number that is not a factor of 2 will cause the script to keep
 dividing over and over resulting in a recursion error. In order to
 fix this, an  if statement can be added so that if n < 1, the script
 can return false and finish. 

~/UW_Python/SP_Python220B_2019/students/matt_casali/lesson02/activity (master)
$ python -m pdb recursive.py 15
> c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py(3)<module>()
-> """
(Pdb) ll
  1     """
  2     recursion for debuging
  3  -> """
  4
  5     import sys
  6
  7
  8     def my_fun(n):
  9         if n == 2:
 10             return True
 11         return my_fun(n / 2)
 12
 13
 14     if __name__ == '__main__':
 15         n = int(sys.argv[1])
 16         print(my_fun(n))
(Pdb) n
> c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py(5)<module>()
-> import sys
(Pdb) n
> c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py(8)<module>()
-> def my_fun(n):
(Pdb) n
> c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py(14)<module>()
-> if __name__ == '__main__':
(Pdb) n
> c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py(15)<module>()
-> n = int(sys.argv[1])
(Pdb) n
> c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py(16)<module>()
-> print(my_fun(n))
(Pdb) pp n
15
(Pdb) ll
  1     """
  2     recursion for debuging
  3     """
  4
  5     import sys
  6
  7
  8     def my_fun(n):
  9         if n == 2:
 10             return True
 11         return my_fun(n / 2)
 12
 13
 14     if __name__ == '__main__':
 15         n = int(sys.argv[1])
 16  ->     print(my_fun(n))
(Pdb) s
--Call--
> c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py(8)my_fun()
-> def my_fun(n):
(Pdb) n
> c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py(9)my_fun()
-> if n == 2:
(Pdb) pp n
15
(Pdb) n
> c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py(11)my_fun()
-> return my_fun(n / 2)
(Pdb) s
--Call--
> c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py(8)my_fun()
-> def my_fun(n):
(Pdb) n
> c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py(9)my_fun()
-> if n == 2:
(Pdb) pp n
7.5
(Pdb) b 5
Breakpoint 1 at c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py:5
(Pdb) c
Traceback (most recent call last):
  File "C:\Users\DakotaDakota\AppData\Local\Programs\Python\Python37-32\lib\pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "C:\Users\DakotaDakota\AppData\Local\Programs\Python\Python37-32\lib\pdb.py", line 1566, in _runscript
    self.run(statement)
  File "C:\Users\DakotaDakota\AppData\Local\Programs\Python\Python37-32\lib\bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py", line 16, in <module>
    print(my_fun(n))
  File "c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py", line 11, in my_fun
    return my_fun(n / 2)
  File "c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py", line 11, in my_fun
    return my_fun(n / 2)
  File "c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py", line 11, in my_fun
    return my_fun(n / 2)
  [Previous line repeated 980 more times]
  File "c:\users\dakotadakota\documents\programming\uw_python\sp_python220b_2019\students\matt_casali\lesson02\activity\recursive.py", line 8, in my_fun
    def my_fun(n):
  File "C:\Users\DakotaDakota\AppData\Local\Programs\Python\Python37-32\lib\bdb.py", line 90, in trace_dispatch
    return self.dispatch_call(frame, arg)
  File "C:\Users\DakotaDakota\AppData\Local\Programs\Python\Python37-32\lib\bdb.py", line 128, in dispatch_call
    if not (self.stop_here(frame) or self.break_anywhere(frame)):
  File "C:\Users\DakotaDakota\AppData\Local\Programs\Python\Python37-32\lib\bdb.py", line 250, in break_anywhere
    return self.canonic(frame.f_code.co_filename) in self.breaks
  File "C:\Users\DakotaDakota\AppData\Local\Programs\Python\Python37-32\lib\bdb.py", line 45, in canonic
    if filename == "<" + filename[1:-1] + ">":
RecursionError: maximum recursion depth exceeded in comparison

